In [12]:
import numpy as np
w=np.array([[0.2, -0.5, 0.1, 2, 1.1], [1.5, 1.3, 2.1, 0, 3.2], [0, 0.25, 0.2, -0.3, -1.2]])
x = np.array([56, 231, 24, 2, 1])
y = 0
dw = np.zeros(w.shape)
print(w)
print(x)
print(y)
print(dw)
print(dw[:,2])
print(x)

[[ 0.2  -0.5   0.1   2.    1.1 ]
 [ 1.5   1.3   2.1   0.    3.2 ]
 [ 0.    0.25  0.2  -0.3  -1.2 ]]
[ 56 231  24   2   1]
0
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[ 0.  0.  0.]
[ 56 231  24   2   1]


In [3]:
print(w.shape[1])
print x.shape[0]
print(np.zeros(w.shape))
num_classes = w.shape[1]
num_train = x.shape[0]
print(num_classes)
print(num_train)

5
5
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
5
5


In [5]:
scores = w.dot(x)
print(scores)
print(scores - scores[y])


[ -96.8   437.9    60.75]
[   0.    534.7   157.55]


In [3]:
# for back propogation example
# forward pass
import numpy as np
W = np.random.randn(5, 10)
X = np.random.randn(10, 3)
D = W.dot(X)
print(W.shape)
print(X.shape)
print(D.shape)
# now suppose we had the gradient on D from above in the circuit
dD = np.random.randn(*D.shape) # same shape as D
dW = dD.dot(X.T) #.T gives the transpose of the matrix
dX = W.T.dot(dD)
print(dW.shape)
print(dX.shape)
print(dD.shape)


(5L, 10L)
(10L, 3L)
(5L, 3L)
(5L, 10L)
(10L, 3L)
(5L, 3L)
