In [1]:
import numpy as np
x1 = np.arange(9.0).reshape((3, 3))
print(x1[1])
x2 = np.arange(3.0)
print(x2[1])
print(np.subtract(x1[1], x2[1]))

[ 3.  4.  5.]
1.0
[ 2.  3.  4.]


In [43]:
# For two loop
import numpy as np
a = np.array([[1,1,1,1],[2,2,2,2]])
print(a)
b = np.array([[1,2,3,4],[1,1,1,1],[1,2,1,9]])
print(b)
print(np.sum(np.square(a[0] - b[2])))

[[1 1 1 1]
 [2 2 2 2]]
[[1 2 3 4]
 [1 1 1 1]
 [1 2 1 9]]
65


In [30]:
# For single loop
import numpy as np
a = np.array([[1,1,1,1],[2,2,2,2]])
print(a)
b = np.array([[1,2,3,4],[1,1,1,1],[1,2,1,9]])
print(b)
print(a[0] -b)
print(np.square(a[0] -b))
print(np.sum(np.square(a[0] - b), axis=1))
dists = np.zeros((2, 3))
#for i in range(2):
#      dists[i] = np.sqrt(np.sum(np.square(a[i] - b), axis=1))

[[1 1 1 1]
 [2 2 2 2]]
[[1 2 3 4]
 [1 1 1 1]
 [1 2 1 9]]
[[ 0 -1 -2 -3]
 [ 0  0  0  0]
 [ 0 -1  0 -8]]
[[ 0  1  4  9]
 [ 0  0  0  0]
 [ 0  1  0 64]]
[14  0 65]


In [23]:
# For no loop
import numpy as np
a = np.array([[1,1,1,1],[2,2,2,2]])
#print(a)
b = np.array([[1,2,3,4],[1,1,1,1],[1,2,1,9]])
#print(b)
c = np.square(a - b[:, np.newaxis])
print(c.sum(axis=2))
print(np.square(a - b[:, np.newaxis]))
#print(np.sum(np.square(a - b[:, np.newaxis])), axis=1)

[[14  6]
 [ 0  4]
 [65 51]]
[[[ 0  1  4  9]
  [ 1  0  1  4]]

 [[ 0  0  0  0]
  [ 1  1  1  1]]

 [[ 0  1  0 64]
  [ 1  0  1 49]]]


In [52]:
# For no loop
import numpy as np
a = np.array([[1,1,1,1],[2,2,2,2],[3,4,6,7]])
#print(a)
b = np.array([[1,2,3,4],[1,1,1,1],[1,2,1,9],[3,5,7,2], [2,2,2,2]])
#print(b)
label = np.array([1,3,1,2,3])
print(label)
a1 = np.sum(np.square(a), axis=1, keepdims = True)
print(a1)
b1 = np.sum(np.square(b), axis=1)
print(b1)
ab2 = np.multiply(np.dot(a,b.T),-2)
print(ab2)
ab = np.add(ab2, b1)
ab = np.add(ab, a1)
dis1 = np.sqrt(ab)
print(dis1)
t1 = dis1[1]
print(t1)
t2 = label[np.argsort(t1)[:2]]
print(t2)
t3 = np.argmax(np.bincount(t2))
print(t3)
#print(np.argmax(np.bincount(np.array([0, 1, 2, 3, 4, 2, 7]))))

[1 3 1 2 3]
[[  4]
 [ 16]
 [110]]
[30  4 87 87 16]
[[ -20   -8  -26  -34  -16]
 [ -40  -16  -52  -68  -32]
 [-114  -40 -160 -170  -80]]
[[ 3.74165739  0.          8.06225775  7.54983444  2.        ]
 [ 2.44948974  2.          7.14142843  5.91607978  0.        ]
 [ 5.09901951  8.60232527  6.08276253  5.19615242  6.78232998]]
[ 2.44948974  2.          7.14142843  5.91607978  0.        ]
[3 3]
3
