In [7]:
import numpy as np
w=np.array([[0.2, -0.5, 0.1, 2, 1.1], [1.5, 1.3, 2.1, 0, 3.2], [0, 0.25, 0.2, -0.3, -1.2]])
x = np.array([56, 231, 24, 2, 1])
print(w)
print(x)

[[ 0.2  -0.5   0.1   2.    1.1 ]
 [ 1.5   1.3   2.1   0.    3.2 ]
 [ 0.    0.25  0.2  -0.3  -1.2 ]]
[ 56 231  24   2   1]


In [8]:
print(w.shape[1])
print(np.zeros(w.shape))
num_classes = w.shape[1]
num_train = x.shape[0]
print(num_classes)
print(num_train)

5
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
5
5


In [9]:
scores = w.dot(x)
print(scores)



[ -96.8   437.9    60.75]


In [10]:
print(w[:,4])
print(w[1,:])
#print(w[:,1] + w[1,:])

[ 1.1  3.2 -1.2]
[ 1.5  1.3  2.1  0.   3.2]


In [19]:
for i in xrange(num_classes):
    print(x[i])

56
231
24
2
1


In [54]:
import numpy as np
x1 = np.array([[56,231,24,2,1],[74,81,71,88,99],[101,2,45,56,65]])
w1 = np.array([[0.2,1.5,0],[-0.5,1.3,0.25],[0.1,2.1,0.2],[2,0,-0.3],[1.1,3.2,-1.2]])
y1 = np.array([2,1,2])
s1 = x1.dot(w1)
print(s1)
correct_res = s1[np.arange(x1.shape[0]), y1]
print(correct_res)
margin = np.maximum(0, s1 - np.matrix(correct_res).T + 1)
print(margin)
loss = 0
loss = np.mean(np.sum(margin, axis=1))
print(loss)
loss += 0.5 * 0.00001 * np.sum(w1 * w1)
print(loss)
#print(np.arrange(x1.shape[0]), y)
#print(s1-s1[:1])

[[ -96.8   437.9    60.75]
 [ 266.3   682.2  -110.75]
 [ 207.2   456.6   -85.3 ]]
[  60.75  682.2   -85.3 ]
[[   0.    378.15    1.  ]
 [   0.      1.      0.  ]
 [ 293.5   542.9     1.  ]]
405.85
405.850128662
